#!/bin/bash

exec 2>&1

############# PROJECT SETUP #############################
echo "Copying source files"
cp -r {{pkg.path}}/static/* {{pkg.svc_data_path}}/.

chmod +x {{pkg.svc_data_path}}
chown -RL hab:hab {{pkg.svc_data_path}}

############# NGINX SETUP #############################
mkdir -p {{pkg.svc_var_path}}/nginx
chown hab:hab {{pkg.svc_var_path}}
